### ISSUE TITLE
Block ID Packager - Doesn't work anymore

### ISSUE THREAD

**Issue by CommanderGL** [CloudWolfYT/cloudwolfyt.github.io#6]
JavaScript Console Error:
```
block-id.js:147  Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'id')
    at parse_output (block-id.js:147:76)
    at get_zip1 (block-id.js:34:5)
    at block-id.js:64:12
```

**Comment by CommanderGL** [comment]
Fixed on Firefox.
but also when using any output (even built in) I get error:
```
Uncaught (in promise) TypeError: tblock[0] is undefined
    parse_output https://cloudwolfyt.github.io/pages/js/block-id.js:147
    get_zip1 https://cloudwolfyt.github.io/pages/js/block-id.js:26
    get_jsons https://cloudwolfyt.github.io/pages/js/block-id.js:64
```
